/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/homepage/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Homepage Cards */
        get: operations["homepage_cards_api_v1_homepage_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/homepage/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_api_v1_homepage_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_v1_activities_get"];
        put?: never;
        /** Create Activity */
        post: operations["create_activity_api_v1_activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Activity */
        delete: operations["delete_activity_api_v1_activities__activity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/my-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Day */
        get: operations["my_day_api_v1_my_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weather-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Weather Risk */
        post: operations["weather_risk_api_v1_weather_risk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        /** Clear */
        delete: operations["clear_api_v1_alerts_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_v1_alerts_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout All
         * @description Revoke every token ever issued for the authenticated account.
         */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Permanently erase the account and every associated record (DPDP erasure).
         *
         *     Removes the credential, the cloud profile backup, the in-app alert inbox
         *     and all registered push tokens. The client is expected to also wipe local
         *     device state after a successful response.
         */
        delete: operations["delete_account_api_v1_auth_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Otp */
        post: operations["request_otp_api_v1_auth_request_otp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Otp */
        post: operations["verify_otp_api_v1_auth_verify_otp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Recover an account with a reset OTP; invalidates all prior tokens.
         */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_users__user_id__profile_get"];
        /** Put Profile */
        put: operations["put_profile_api_v1_users__user_id__profile_put"];
        post?: never;
        /**
         * Delete Profile
         * @description Permanently remove this user's cloud backup (right-to-erasure).
         */
        delete: operations["delete_profile_api_v1_users__user_id__profile_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/push-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Push Token
         * @description Register the device's Expo/FCM push token for server->device alerts.
         */
        post: operations["register_push_token_api_v1_users__user_id__push_token_post"];
        /** Unregister Push Token */
        delete: operations["unregister_push_token_api_v1_users__user_id__push_token_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notifications
         * @description The durable alert inbox for this user (server-side archive).
         */
        get: operations["list_notifications_api_v1_users__user_id__notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/notifications/{notification_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ack Notification
         * @description Mark a single archive entry as read (clears its unread badge).
         */
        post: operations["ack_notification_api_v1_users__user_id__notifications__notification_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_admin_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_admin_users__user_id__get"];
        /** Update User */
        put: operations["update_user_api_admin_users__user_id__put"];
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_admin_users__user_id__activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Activity */
        delete: operations["delete_activity_api_admin_users__user_id__activities__activity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_admin_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_api_admin_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Alert */
        put: operations["update_alert_api_admin_alerts__alert_id__put"];
        post?: never;
        /** Delete Alert */
        delete: operations["delete_alert_api_admin_alerts__alert_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/alerts/{alert_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alert Impact */
        get: operations["alert_impact_api_admin_alerts__alert_id__impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/push/broadcast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push Broadcast
         * @description Send a push notification to every registered device (operator demo).
         */
        post: operations["push_broadcast_api_admin_push_broadcast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** Id */
            id: string;
            type: components["schemas"]["ActivityType"];
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Days
             * @default []
             */
            days: number[];
            /** Preferred Start */
            preferred_start?: string | null;
            /** Preferred End */
            preferred_end?: string | null;
            loc?: components["schemas"]["GeoPoint"] | null;
        };
        /** ActivityInput */
        ActivityInput: {
            type: components["schemas"]["ActivityType"];
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Days
             * @default []
             */
            days: number[];
            /** Preferred Start */
            preferred_start?: string | null;
            /** Preferred End */
            preferred_end?: string | null;
            location?: components["schemas"]["GeoPoint"] | null;
        };
        /**
         * ActivityType
         * @enum {string}
         */
        ActivityType: "run" | "cycle" | "outdoor_gym" | "commute" | "school" | "farm_irrigation" | "farm_frost" | "farm_planting" | "beach" | "surf" | "event" | "travel";
        /**
         * ActivityWindow
         * @description A graded time slot for an activity within a day.
         */
        ActivityWindow: {
            activity: components["schemas"]["ActivityType"];
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Score */
            score: number;
            /** Level */
            level: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Factors
             * @default []
             */
            factors: components["schemas"]["FactorScore"][];
        };
        /** AlertCreate */
        AlertCreate: {
            /**
             * Severity
             * @default orange
             */
            severity: string;
            /**
             * Event Type
             * @default heavy_rain
             */
            event_type: string;
            /**
             * Headline
             * @default Heavy rain expected
             */
            headline: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Region
             * @default Pune
             */
            region: string;
            /**
             * Impact
             * @default []
             */
            impact: string[];
            /**
             * Valid Hours
             * @default 24
             */
            valid_hours: number;
            /**
             * Radius Km
             * @default 40
             */
            radius_km: number;
        };
        /**
         * AlertPhase
         * @enum {string}
         */
        AlertPhase: "official" | "derived" | "informational";
        /** AlertSimulationRequest */
        AlertSimulationRequest: {
            /** @default orange */
            severity: components["schemas"]["WarningSeverity"];
            /**
             * Event Type
             * @default heavy_rain
             */
            event_type: string;
            /**
             * Headline
             * @default Heavy rain expected
             */
            headline: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Region
             * @default Pune
             */
            region: string;
            /**
             * Impact
             * @default [
             *       "flooding on low-lying roads",
             *       "traffic disruption",
             *       "tree fall risk"
             *     ]
             */
            impact: string[];
            /**
             * Valid Hours
             * @default 24
             */
            valid_hours: number;
            center?: components["schemas"]["GeoPoint"] | null;
            /** Radius Km */
            radius_km?: number | null;
        };
        /** AlertSummary */
        AlertSummary: {
            /** Id */
            id: string;
            severity: components["schemas"]["WarningSeverity"];
            /** Event Type */
            event_type: string;
            /** Headline */
            headline: string;
            /** Region */
            region: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
        /** AlertUpdate */
        AlertUpdate: {
            /** Severity */
            severity?: string | null;
            /** Event Type */
            event_type?: string | null;
            /** Headline */
            headline?: string | null;
            /** Detail */
            detail?: string | null;
            /** Region */
            region?: string | null;
            /** Valid Hours */
            valid_hours?: number | null;
        };
        /** AppNotification */
        AppNotification: {
            /** Id */
            id: string;
            /** Alert Id */
            alert_id: string;
            severity: components["schemas"]["WarningSeverity"];
            /** Event Type */
            event_type: string;
            /** Headline */
            headline: string;
            /** Body */
            body: string;
            /** Region */
            region: string;
            /**
             * Read
             * @default false
             */
            read: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AskIntent
         * @enum {string}
         */
        AskIntent: "should_i_run" | "should_i_travel" | "should_i_irrigate" | "beach_safety" | "school_commute" | "outdoor_event" | "frost_risk" | "general_brief";
        /** AskRequest */
        AskRequest: {
            /** User Id */
            user_id: string;
            /** Question */
            question: string;
            /**
             * City
             * @default pune
             */
            city: string | null;
            /** Scenario */
            scenario?: string | null;
            /**
             * Context
             * @default {}
             */
            context: Record<string, never>;
        };
        /** AskResponse */
        AskResponse: {
            intent: components["schemas"]["AskIntent"];
            /** Answer */
            answer: string;
            /**
             * Verbatim
             * @default false
             */
            verbatim: boolean;
            /**
             * Why
             * @default []
             */
            why: string[];
            /** Score */
            score?: number | null;
            /** Level */
            level?: string | null;
            source: components["schemas"]["ProviderName"];
        };
        /** AuthOut */
        AuthOut: {
            /** User Id */
            user_id: string;
            /** Token */
            token: string;
            /**
             * Verified
             * @default true
             */
            verified: boolean;
            /**
             * Contact Verification Required
             * @default false
             */
            contact_verification_required: boolean;
            /**
             * Message
             * @default ok
             */
            message: string;
        };
        /** CardExplanation */
        CardExplanation: {
            /** Why Shown */
            why_shown: string;
            source: components["schemas"]["ProviderName"];
            /** Confidence */
            confidence: number;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
        /**
         * CardType
         * @enum {string}
         */
        CardType: "severe_warning" | "my_day" | "mausam_brief" | "aqi" | "uv" | "pollen" | "humidity" | "running_window" | "cycling_window" | "outdoor_comfort" | "school_commute" | "work_commute" | "rain_timeline" | "fog_alert" | "farm_irrigation" | "farm_frost" | "farm_planting" | "beach_safety" | "tide_info" | "surf_conditions" | "event_weather" | "travel_destination" | "packing_advisor" | "sunrise_sunset";
        /** DisasterAlert */
        DisasterAlert: {
            /** Id */
            id: string;
            severity: components["schemas"]["WarningSeverity"];
            /** Event Type */
            event_type: string;
            /** Headline */
            headline: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Region */
            region: string;
            polygon: components["schemas"]["GeoPolygon"];
            /**
             * Issued By
             * @default IMD
             */
            issued_by: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
            /**
             * Actionable
             * @default []
             */
            actionable: string[];
        };
        /** FactorScore */
        FactorScore: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /**
             * Weight
             * @default 0
             */
            weight: number;
            /** Detail */
            detail?: string | null;
        };
        /** GeoPoint */
        GeoPoint: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Geohash */
            geohash?: string | null;
            /** Name */
            name?: string | null;
            /** District */
            district?: string | null;
            /** State */
            state?: string | null;
        };
        /**
         * GeoPolygon
         * @description GeoJSON-style polygon (ring of [lon, lat] pairs, closed).
         */
        GeoPolygon: {
            /**
             * Type
             * @default Polygon
             */
            type: string;
            /**
             * Coordinates
             * @description ring: [[lon,lat],...]
             */
            coordinates: number[][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomepageCard */
        HomepageCard: {
            /** Id */
            id: string;
            type: components["schemas"]["CardType"];
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Priority */
            priority: number;
            phase?: components["schemas"]["AlertPhase"] | null;
            /**
             * Data
             * @default {}
             */
            data: Record<string, never>;
            explanation: components["schemas"]["CardExplanation"];
            provenance: components["schemas"]["Provenance"];
        };
        /** HomepageResponse */
        HomepageResponse: {
            /** User Id */
            user_id: string;
            /** City */
            city: string | null;
            /**
             * Personas
             * @default []
             */
            personas: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: Record<string, never>;
            /** Cards */
            cards: components["schemas"]["HomepageCard"][];
        };
        /** MyDayResponse */
        MyDayResponse: {
            /** User Id */
            user_id: string;
            /** Date */
            date: string;
            /** City */
            city: string | null;
            /** Summary */
            summary: string;
            /** Best Window */
            best_window: string;
            /**
             * Slots
             * @default []
             */
            slots: components["schemas"]["ActivityWindow"][];
        };
        /** NotificationListOut */
        NotificationListOut: {
            /** User Id */
            user_id: string;
            /**
             * Unread
             * @default 0
             */
            unread: number;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["AppNotification"][];
        };
        /** OtpOut */
        OtpOut: {
            /** User Id */
            user_id: string;
            purpose: components["schemas"]["OtpPurpose"];
            /** Sent To */
            sent_to?: string | null;
            /** Ttl Minutes */
            ttl_minutes: number;
            /** Dev Code */
            dev_code?: string | null;
        };
        /**
         * OtpPurpose
         * @enum {string}
         */
        OtpPurpose: "verify_email" | "verify_phone" | "reset_password";
        /**
         * OtpRequest
         * @description Ask the server to generate + deliver a one-time-password.
         *
         *     ``contact`` is only needed when binding a contact during registration that
         *     was not supplied there (it must match the account's own contact otherwise).
         */
        OtpRequest: {
            /** User Id */
            user_id: string;
            purpose: components["schemas"]["OtpPurpose"];
            /** Contact */
            contact?: string | null;
        };
        /** OtpVerifyRequest */
        OtpVerifyRequest: {
            /** User Id */
            user_id: string;
            purpose: components["schemas"]["OtpPurpose"];
            /** Code */
            code: string;
        };
        /**
         * ProfileSync
         * @description The mobile UserProfile payload used to move a profile between devices.
         *
         *     The client stores this locally (AsyncStorage) and can PUT it to the server,
         *     then GET it back on another device to restore the same experience.
         */
        ProfileSync: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Name Hi */
            name_hi?: string | null;
            /**
             * Personas
             * @default []
             */
            personas: string[];
            /**
             * Conditions
             * @default []
             */
            conditions: string[];
            /**
             * Activities
             * @default []
             */
            activities: components["schemas"]["SyncActivity"][];
            /**
             * Locations
             * @default []
             */
            locations: components["schemas"]["SyncLocation"][];
            /**
             * City
             * @default pune
             */
            city: string;
            /**
             * Language
             * @default en
             */
            language: string;
            /**
             * Behavior Bias
             * @default {}
             */
            behavior_bias: {
                [key: string]: number;
            };
        };
        /** ProfileSyncOut */
        ProfileSyncOut: {
            /** User Id */
            user_id: string;
            profile?: components["schemas"]["ProfileSync"] | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * Provenance
         * @description Attribution + validity carried on every piece of weather data/card.
         */
        Provenance: {
            source: components["schemas"]["ProviderName"];
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
            /**
             * Licence
             * @default CC-BY-4.0 (open govt); verify terms per SIH
             */
            licence: string;
            /** Raw Payload Ref */
            raw_payload_ref?: string | null;
        };
        /**
         * ProviderName
         * @enum {string}
         */
        ProviderName: "imd" | "cpcb" | "incois" | "isro" | "open_meteo" | "mock" | "crowdsource";
        /** PushBroadcast */
        PushBroadcast: {
            /**
             * Title
             * @default Mausam
             */
            title: string;
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Region
             * @default All India
             */
            region: string;
            /**
             * Severity
             * @default yellow
             */
            severity: string;
        };
        /** PushTarget */
        PushTarget: {
            /** User Id */
            user_id: string;
            /** Registered City */
            registered_city: string | null;
            /** In Polygon */
            in_polygon: boolean;
            /** Headline */
            headline: string;
            /** Body */
            body: string;
            /**
             * Fcm Payload
             * @default {}
             */
            fcm_payload: Record<string, never>;
        };
        /** PushTokenIn */
        PushTokenIn: {
            /** Token */
            token: string;
            /**
             * Platform
             * @default android
             */
            platform: string;
        };
        /**
         * RegisterRequest
         * @description Create a mobile account that owns a synced profile across devices.
         *
         *     ``email`` / ``phone`` are optional at registration but strongly advised:
         *     they unlock OTP verification and self-serve password recovery (the only
         *     way to recover an account today).
         */
        RegisterRequest: {
            /** User Id */
            user_id: string;
            /** Password */
            password: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /**
         * ResetPasswordRequest
         * @description Recover an account using a reset OTP instead of the old password.
         */
        ResetPasswordRequest: {
            /** User Id */
            user_id: string;
            /** Code */
            code: string;
            /** New Password */
            new_password: string;
        };
        /** RiskRequest */
        RiskRequest: {
            /** User Id */
            user_id: string;
            /**
             * Activity
             * @description free-text, e.g. 'run', 'beach', 'commute'
             */
            activity: string;
            /**
             * City
             * @default pune
             */
            city: string;
            /** Scenario */
            scenario?: string | null;
        };
        /** SimulationResult */
        SimulationResult: {
            alert: components["schemas"]["DisasterAlert"];
            /**
             * Affected Users
             * @default []
             */
            affected_users: components["schemas"]["PushTarget"][];
        };
        /**
         * SyncActivity
         * @description A scheduled activity on the mobile profile.
         */
        SyncActivity: {
            /** Type */
            type: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** Label Hi */
            label_hi?: string | null;
            /**
             * Time
             * @default 09:00
             */
            time: string;
        };
        /**
         * SyncLocation
         * @description A saved place (home/work/school/farm) on the mobile profile.
         */
        SyncLocation: {
            /**
             * Type
             * @default home
             */
            type: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Personas */
            personas?: string[] | null;
            /** Language */
            language?: string | null;
            /** City */
            city?: string | null;
            /** Health */
            health?: Record<string, never> | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WarningSeverity
         * @enum {string}
         */
        WarningSeverity: "green" | "yellow" | "orange" | "red";
        /** LoginRequest */
        app__admin__router__LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginRequest */
        app__models__schemas__LoginRequest: {
            /** User Id */
            user_id: string;
            /** Password */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    homepage_cards_api_v1_homepage_cards_get: {
        parameters: {
            query: {
                /** @description User identifier */
                user_id: string;
                /** @description City anchor for personalization */
                city?: string | null;
                /** @description Demo scenario override (see scenarios) */
                scenario?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomepageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenarios_api_v1_homepage_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    ask_api_v1_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_v1_activities_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_activity_api_v1_activities_post: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_activity_api_v1_activities__activity_id__delete: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_day_api_v1_my_day_get: {
        parameters: {
            query: {
                user_id: string;
                city?: string | null;
                scenario?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyDayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weather_risk_api_v1_weather_risk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_v1_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSummary"][];
                };
            };
        };
    };
    clear_api_v1_alerts_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    simulate_api_v1_alerts_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertSimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__models__schemas__LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_v1_auth_account_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_otp_api_v1_auth_request_otp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_otp_api_v1_auth_verify_otp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_users__user_id__profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSyncOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_api_v1_users__user_id__profile_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileSync"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSyncOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_v1_users__user_id__profile_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_push_token_api_v1_users__user_id__push_token_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unregister_push_token_api_v1_users__user_id__push_token_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_v1_users__user_id__notifications_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_notification_api_v1_users__user_id__notifications__notification_id__ack_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__admin__router__LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_admin_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_api_admin_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_admin_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_admin_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_admin_users__user_id__activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_activity_api_admin_users__user_id__activities__activity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                activity_id: string;
            };
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_admin_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_api_admin_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_api_admin_alerts__alert_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_api_admin_alerts__alert_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alert_impact_api_admin_alerts__alert_id__impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_broadcast_api_admin_push_broadcast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mausam_admin_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushBroadcast"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
