import type { Homepage } from './engine';

export function buildPrompt(hp: Homepage): string {
  const example = hp.cards[0];
  const exampleJson = example
    ? JSON.stringify(
        {
          id: example.id,
          type: example.type,
          title: example.title,
          summary: example.summary,
          priority: example.priority,
          phase: example.phase,
          data: { score: example.score, level: example.level, best_window: example.bestWindow, factors: example.factors?.map((f) => ({ name: f.name, value: f.value, impact: f.impact })) },
          explanation: { why_shown: example.explanation.why, source: example.explanation.source, confidence: example.explanation.confidence, ranking: example.explanation.ranking },
          provenance: example.provenance,
        },
        null,
        2,
      )
    : '{}';

  return `# Mausam 2.0 — UI build brief for OpenCode
Repo: https://github.com/shivv23/MausamSIH2026 (SIH 2026 · PS 26076 · MoES/IMD · Team BugNotFound)
Stack: mobile/ = React Native + Expo SDK 57 + TypeScript (Hermes) · backend/ = FastAPI (Python 3.12)
Goal: Rebuild \`mobile/src/screens\` into a polished, production-quality personalised weather homepage that turns official IMD data into DECISIONS, not data. Keep the API contract in docs/api-contract.md unchanged; extend \`types.ts\` where noted.

## 0. Working rules
- Read mobile/AGENTS.md first (Expo SDK 57 docs). Do not downgrade Expo.
- Keep everything offline-first and cheap: target ₹7,000 Android phones. No heavy animation libs; use Reanimated only if already installed, else Animated API.
- Every card MUST render \`explanation.why_shown\`, \`explanation.source\`, \`explanation.confidence\` and \`provenance.valid_until\`. This is a hard product requirement ("trust through transparency").
- Official IMD Orange/Red warnings are pinned above ALL personalised cards and are never generated by an LLM.
- All copy goes through i18n (EN + HI bundled; TA/TE/BN/MR/GU/KN/ML/OR/PA lazy-loaded). No hard-coded strings.

## 1. Design tokens (create mobile/src/theme.ts — extend the existing one)
colors:
  primary #1565C0 · primaryLight #64B5F6 · primaryDeep #0F2A4A
  surface #F8FAFE · card #FFFFFF · text #0F172A · textMuted #64748B · hairline rgba(15,23,42,0.06)
  score: excellent #2E9E4A · good #7CB342 · fair #F2B100 · poor #F57C00 · avoid #E53935
  severity: green #2E9E4A · yellow #F2B100 · orange #F57C00 · red #E53935
  phase: official = severity colour bg + white text · derived = #E3F2FD bg / #1565C0 text · informational = #F1F5F9 bg / #64748B text
  persona accents: health #2E7D32 · fitness #F57C00 · beach #1565C0 · travel #6A1B9A · parent #C2185B · agriculture #00695C · commuter #455A64 · events #E65100 (each with a 10%-tint "soft" background)
hero gradients (by condition, darker variant at night):
  sunny  linear(160°, #38BDF8 → #0EA5E9 → #1D4ED8)
  partly linear(160°, #5EEAD4 → #38BDF8 → #2563EB)
  rain   linear(160°, #475569 → #64748B → #1D4ED8)
  storm  linear(160°, #1E1B4B → #312E81 → #0F172A)
  haze   linear(160°, #8C7B6B → #A38F7C → #6B5B4E)
  hot    linear(160°, #F59E0B → #F97316 → #DC2626)
  cold   linear(160°, #60A5FA → #818CF8 → #475569)
  night  linear(160°, #0B1F3A → #1E3A8A → #0B1220)
type (Plus Jakarta Sans or system; Noto Sans Devanagari for HI):
  display 68/0.9 extralight (hero temp) · h1 22/700 · h2 15/800 · body 13/400 lh 1.45 · caption 11/600 · badge 9.5/800 uppercase tracking 0.08em
radius: card 22 · hero 28 · sheet 28 (top) · chip 999 · icon-tile 16
spacing: screen padding 16 · card padding 16 · card gap 12
elevation: card = shadow(0,10,28,-16, rgba(16,24,40,.18)) + 1px hairline ring
motion: card enter = fade+translateY(8px) 260ms ease-out, stagger 60ms · sheet = translateY 320ms cubic-bezier(.2,.8,.2,1) · score ring arc animates 800ms

## 2. Navigation (bottom tabs, 5)
Home · My Day · Ask · Alerts · Me. Active tab: icon in 10% primary pill + primary label. Explanation sheet is a modal bottom-sheet reachable from any card.

## 3. Screens

### 3.1 Onboarding (4 steps, skippable after step 1)
0 Welcome: full-bleed gradient (#0F2A4A→#1565C0→#38BDF8), logo tile, headline "Weather that understands you", 3 trust bullets (official data only / on-device / alerts only when they matter), language toggle EN/HI, CTA "Get started".
1 Personas: 2-col grid of 8 persona tiles (emoji, label, one-line desc). Max 3; first selected shows ★ = primary. Next disabled until ≥1.
2 Context: name, home city chips (pune, delhi, mumbai, chennai, kochi, chandigarh, kolkata, bengaluru), health condition chips (asthma, pollen_allergy, uv_sensitive, heat_sensitive), privacy note.
3 Notifications: briefing time chips (06:00–08:00), toggles (Severe alerts = locked ON, Activity nudges, AQI>150), quiet hours 22:00–06:00. CTA "Build my homepage".
Persist profile with MMKV; call GET /api/v1/homepage/cards?user_id=…&city=… on finish.

### 3.2 Home (the PS 26076 deliverable)
Order top→bottom:
1 Header: "Good morning, {name}" · freshness line with green/amber dot "Updated 6 min ago · IMD · CPCB" · bell with unread count · avatar.
2 Offline banner (amber) when serving expo-sqlite cache: "Offline — showing cached homepage from 07:42" + Retry.
3 Hero card: condition gradient, location pill, 68px temperature, condition label, "Feels like · H/L", 4 glass stat tiles (AQI w/ CPCB band dot, UV w/ WHO band, Humidity, Wind). Rain/storm: subtle animated rain lines.
4 Pinned official warning card(s): white card, 2px severity ring + left stripe, pulsing dot, "OFFICIAL · IMD · RED" label, "Never AI-generated" chip, headline, body, ✓ action chips, "Valid 36h · Confidence 99%", Share + "Safety steps" buttons.
5 Section "For you now" + sub "Ranked by interest × context × urgency" + horizontal persona filter chips (All + user's personas, ★ on primary).
6 Ranked ImpactCards (see §4), interleaved: 2 cards → MyDayCard → 2 cards → BriefCard → remaining → HourlyStrip → DailyStrip.
7 Footer: "Every card carries source, confidence & validity. Data: IMD · CPCB · INCOIS · ISRO" + "Report inaccuracy".

### 3.3 My Day
3 KPI tiles (Good to go / Consider shifting / Avoid counts). Vertical timeline: time column, status dot, card with activity label, weather note (temp · AQI · rain%), 44px score ring, status pill, suggestion line ("Shift to 6:00–7:30 AM", "Leave 30 min early", "Book covered fallback"). Red alert forces all items to Avoid. "Add activity" dashed button.

### 3.4 Ask Mausam
Chat UI. Bot bubbles white w/ hairline; user bubbles primary. Under each answer: "Answered from IMD hourly + CPCB AQI · template, not free-form AI". Suggested-question chips scroll above the input. Answers are TEMPLATE-FIRST from the same impact models (run/cycle, rain at pickup, swim safety, irrigation/frost, packing, AQI/mask, heat). Unknown → explain scope + suggest chips.

### 3.5 Alerts
Segmented control Official / Derived / Info with counts. Rows: icon tile, title + phase badge, 2-line summary, "source · time". Below: "Notification priority" explainer with 5 bars (Severity × Location × Activity × Time × Preference) and quiet-hours note; "Data providers" list with status dot + latency and fallback chain note.

### 3.6 Me (Profile)
Avatar/name/city; Personas (primary tagged); Health profile; Saved places (home/work/school/farm); Activities with times; Notifications (briefing, severe=locked, nudges, AQI threshold, quiet hours); Language (EN/HI + regional list); Units; Data & privacy (on-device note, cache size); "Redo onboarding"; version footer.

## 4. Component inventory (mobile/src/components/)
- HeroCard({weather, city, hour, lang})
- WarningCard({card, onExplain, compact?}) — official orange/red only
- ImpactCard({card, rank, onExplain}) — icon tile (persona soft bg) · title + PhaseBadge · summary · ScoreRing(64) with level label · optional "Best window" chip · up to 3 factor chips (↗ good / ↘ bad / – neutral) · optional ✓ action chips · footer "source · confidence%" + "Why? ›"
- ScoreRing({score, label, size}) — SVG arc, colour by score band, 800ms animation
- PhaseBadge({phase, severity})
- MyDayCard({items}) → navigates to My Day
- BriefCard({text}) — gradient #0F2A4A→#1565C0, sparkle icon, "Template-first · zero hallucination", speaker button (TTS)
- HourlyStrip({hourly}) — 24 tiles, "Now" tile filled primary, rain% turns blue ≥40%
- DailyStrip({daily}) — 5 rows with lo–hi range bar (gradient #38BDF8→#F59E0B)
- ExplainSheet({card}) — header w/ icon+title+badge · "Why am I seeing this?" · Ranking breakdown (6 bars with weights w0.30/0.20/0.25/0.10/0.10/0.05 and Σ) · "What drove the score" factor grid + ring · Provenance box (source, issued, valid until, confidence bar, licence) · feedback (Helpful / Not helpful / Inaccurate → POST user_feedback with weather snapshot) · "Show fewer like this"
- PersonaChips, OfflineBanner, SectionHeader, Chip, Toggle, TabBar

## 5. Data contract (do not break)
GET /api/v1/homepage/cards?user_id&city&scenario → { user_id, city, personas[], generated_at, metadata{dataFreshness, providerStatus[]}, cards[] }
Extend HomepageCard.data (backend already sets score/level/best_window/factors) and ADD to explanation: \`ranking: {interest, context, urgency, time, location, behavior}\` (0–1 each) so the sheet can draw the breakdown.
Example card from the current prototype state (${hp.user.name} · ${hp.city.name} · ${hp.scenario.label}):
\`\`\`json
${exampleJson}
\`\`\`
Ranking: Score = 0.30·Interest + 0.20·Context + 0.25·Urgency + 0.10·Time + 0.10·Location + 0.05·Behavior; official orange/red pinned regardless. Max one card per type; cap 8 + pinned.
Scenarios for demo QA: clear, clean_air_morning, aqi_spike, heatwave, rainy_commute, cyclone, beach_day, frost_night. Demo users: ananya (fitness, health, commuter; asthma; Pune), ramesh (agriculture, commuter; Chandigarh; HI), asha (parent, health, events; pollen_allergy; Mumbai).

## 6. Behaviours
- Optimistic render from expo-sqlite cache, then refresh; show OfflineBanner when stale.
- Pull-to-refresh; skeleton cards (not spinners) on cold start; cold start < 2.5 s, homepage p95 < 500 ms.
- Persona filter chips filter cards client-side (pinned always visible).
- Hour-of-day drives greeting, hero gradient (night variants) and time-relevance weighting.
- Language switch re-renders all copy instantly; HI uses Noto Sans Devanagari.
- Accessibility: 44pt touch targets, colour never the only signal (level text next to rings), dynamic type up to 130%, screen-reader labels "Best time to run, score 72 out of 100, Good".
- Quiet hours 22:00–06:00: only RED official alerts notify.

## 7. Acceptance checklist
[ ] Home renders all 8 scenarios × 3 demo users without layout breaks (390×844 and 360×740)
[ ] Cyclone scenario shows 2 pinned RED cards above everything; My Day items all "Avoid"
[ ] Every card opens ExplainSheet with why/ranking/factors/provenance/feedback
[ ] Offline mode shows banner and cached cards; retry works
[ ] EN ↔ HI toggle changes 100% of visible strings
[ ] Lighthouse-equivalent perf: no jank on a 2 GB RAM device; APK ≈ 25 MB

## 8. Suggested order of work
1 theme.ts tokens + i18n scaffold → 2 primitives (ScoreRing, PhaseBadge, Chip) → 3 HeroCard/ImpactCard/WarningCard → 4 Home screen with cache+refresh → 5 ExplainSheet → 6 Onboarding → 7 My Day / Alerts / Me → 8 Ask (template answers) → 9 QA matrix across scenarios.
`;
}
